version: 2

sources:
  - name: gz_raw_data
    description: dataset containing raw data sources
    tables:
      - name: raw_gz_product
        description: table containing product id ssociated with purchase price of each product
        columns:
          - name: products_id
            description: product identifier
            tests:
              - unique
          - name: purchSE_PRICE
            description: product purchase price
        
      - name: raw_gz_sales
        description: table of order id and associated product id along with revenue generated and quantity of products sold
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness: 
          
          warn_after:
            count: 90
            period: day
        
        columns:
          - name: date_date
            description: date of purchase
          - name: order_id
            description: order identifier
          - name: pdt_id
            description: product identifier
            tests:
                - unique:
                    column_name: "(orders_id || '-' || pdt_id)"
                - not_null
          - name: revenue
            description: revenue generated from each order made of a product
          - name: quantity
            description: number of products sold
      - name: raw_gz_ship
        description: table containing order id and associated shipping fees, logistics cost, shipping costs for each order
        columns:
          - name: orders_id
            description: order identifier
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee per order
          - name: shipping_fee_1
            description: shipping fee per order
          - name: log_cost
            description: logistics cost
          - name: ship_cost
            description: shipping cost per order

        
